In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv(r"C:\Users\gayat\DATA VISUALIZATION\data_visualization\other_classes\Train_details_22122017.csv")
dataset.head()

C:\Users\gayat\AppData\Local\Temp\ipykernel_17560\4042235641.py:1: DtypeWarning: Columns (0,2,7) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv(r"C:\Users\gayat\DATA VISUALIZATION\data_visualization\other_classes\Train_details_22122017.csv")

,Train No,Train Name,SEQ,Station Code,Station Name,Arrival time,Departure Time,Distance,Source Station,Source Station Name,Destination Station,Destination Station Name
0,107,SWV-MAO-VLNK,1,SWV,SAWANTWADI R,00:00:00,10:25:00,0,SWV,SAWANTWADI ROAD,MAO,MADGOAN JN.
1,107,SWV-MAO-VLNK,2,THVM,THIVIM,11:06:00,11:08:00,32,SWV,SAWANTWADI ROAD,MAO,MADGOAN JN.
2,107,SWV-MAO-VLNK,3,KRMI,KARMALI,11:28:00,11:30:00,49,SWV,SAWANTWADI ROAD,MAO,MADGOAN JN.
3,107,SWV-MAO-VLNK,4,MAO,MADGOAN JN.,12:10:00,00:00:00,78,SWV,SAWANTWADI ROAD,MAO,MADGOAN JN.
4,108,VLNK-MAO-SWV,1,MAO,MADGOAN JN.,00:00:00,20:30:00,0,MAO,MADGOAN JN.,SWV,SAWANTWADI ROAD

### **Train Number, Station path, Station priority, Arrival Time, Departure Time, Source Station, Destination Station, Train Type, Train Speed, Actual Arrival, Actual Departure(Actual data is kind of constrained within a random value [-10,10])**
### **Track type, Number of tracks available, Distance from One Station to Another Station**
### **Random problems also created  synthetically like (one train arriving really late) (one train stopping at some point)**

## **let's first create 15 stations and 20 trains**

In [59]:
data_frame = pd.DataFrame(columns=["from", "to", "distance"])

In [60]:
number_of_stations = 5

In [52]:
data_frame.head()

  from   to  distance
0  s_0  s_8        20
1  s_8  s_0        20
2  s_1  s_9         5
3  s_9  s_1         5
4  s_2  s_6        29

In [61]:
stations = []
for i in range(number_of_stations):
    stations.append(f"s_{i}")

In [54]:
import numpy.random as nr

In [62]:
#for the first 15 stations we'll do bidirectional
for i in stations:
    distance = nr.randint(1,30)
    to_station = nr.choice(stations)
    while to_station  == i:
        to_station = nr.choice(stations)
    data_frame.loc[len(data_frame)] = [i, to_station, distance]
    data_frame.loc[len(data_frame)] = [to_station, i, distance]

In [63]:
data_frame.head()

  from   to  distance
0  s_0  s_3        24
1  s_3  s_0        24
2  s_1  s_3         1
3  s_3  s_1         1
4  s_2  s_3        28

In [39]:
for i in range(number_of_stations):
    from_station = nr.choice(stations)
    to_station = nr.choice(stations)
    distance = nr.randint(1,30)
    while to_station  == from_station:
        to_station = nr.choice(stations)
    data_frame.loc[len(data_frame)] = [from_station, to_station, distance]
    data_frame.loc[len(data_frame)] = [to_station, from_station, distance]

In [40]:
data_frame.head()

  from   to  distance
0  s_0  s_8        20
1  s_8  s_0        20
2  s_1  s_9         5
3  s_9  s_1         5
4  s_2  s_6        29

In [41]:
data_frame.to_csv("stations.csv", index = False)

In [68]:
import pandas as pd
import plotly.graph_objects as go

stations = list(set(data_frame['from']).union(data_frame['to']))
import numpy as np
angle = np.linspace(0, 2*np.pi, len(stations), endpoint=False)
pos = {station: (np.cos(a), np.sin(a)) for station, a in zip(stations, angle)}

edge_x = []
edge_y = []
for _, row in data_frame.iterrows():
    x0, y0 = pos[row['from']]
    x1, y1 = pos[row['to']]
    edge_x += [x0, x1, None]
    edge_y += [y0, y1, None]

edge_trace = go.Scatter(
    x=edge_x, y=edge_y,
    line=dict(width=1, color='#888'),
    mode='lines'
)

node_x = [pos[s][0] for s in stations]
node_y = [pos[s][1] for s in stations]

node_trace = go.Scatter(
    x=node_x, y=node_y,
    mode='markers+text',
    text=stations,
    textposition="top center",
    marker=dict(size=15, color='#00CC96')
)

fig = go.Figure(data=[edge_trace, node_trace])
fig.update_layout(
    title="Railway Network",
    showlegend=False,
    xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
    yaxis=dict(showgrid=False, zeroline=False, showticklabels=False)
)
fig.show()